In [1]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Reading the Dataset
dataset = pd.read_csv('Concrete_Data_Yeh.csv')

In [3]:
dataset

,cement,slag,flyash,water,superplasticizer,coarseaggregate,fineaggregate,age,csMPa
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30
...,...,...,...,...,...,...,...,...,...
1025,276.4,116.0,90.3,179.6,8.9,870.1,768.3,28,44.28
1026,322.2,0.0,115.6,196.0,10.4,817.9,813.4,28,31.18
1027,148.5,139.4,108.6,192.7,6.1,892.4,780.0,28,23.70
1028,159.1,186.7,0.0,175.6,11.3,989.6,788.9,28,32.77
1029,260.9,100.5,78.3,200.6,8.6,864.5,761.5,28,32.40

In [4]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [5]:
dataset

,cement,slag,flyash,water,superplasticizer,coarseaggregate,fineaggregate,age,csMPa
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30
...,...,...,...,...,...,...,...,...,...
1025,276.4,116.0,90.3,179.6,8.9,870.1,768.3,28,44.28
1026,322.2,0.0,115.6,196.0,10.4,817.9,813.4,28,31.18
1027,148.5,139.4,108.6,192.7,6.1,892.4,780.0,28,23.70
1028,159.1,186.7,0.0,175.6,11.3,989.6,788.9,28,32.77
1029,260.9,100.5,78.3,200.6,8.6,864.5,761.5,28,32.40

In [6]:
indep=dataset[['cement', 'slag', 'flyash','water', 'superplasticizer','coarseaggregate','fineaggregate','age']]
dep=dataset['csMPa']

In [7]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [9]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
param_grid = {'criterion':['mse','mae','friedman_mse'],
              'max_features': ['auto','sqrt','log2'],
              'splitter':['best','random']} 



grid = GridSearchCV(DecisionTreeRegressor(), param_grid, refit = True, verbose = 3,n_jobs=-1) 
   
# fitting the model for grid search 
grid.fit(X_train, y_train)

C:\Users\Madhu\Anaconda3\envs\ML\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.

Fitting 3 folds for each of 18 candidates, totalling 54 fits

[Parallel(n_jobs=-1)]: Done  24 tasks      | elapsed:    7.4s
[Parallel(n_jobs=-1)]: Done  54 out of  54 | elapsed:    7.5s finished
C:\Users\Madhu\Anaconda3\envs\ML\lib\site-packages\sklearn\model_selection\_search.py:814: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)

GridSearchCV(cv='warn', error_score='raise-deprecating',
             estimator=DecisionTreeRegressor(criterion='mse', max_depth=None,
                                             max_features=None,
                                             max_leaf_nodes=None,
                                             min_impurity_decrease=0.0,
                                             min_impurity_split=None,
                                             min_samples_leaf=1,
                                             min_samples_split=2,
                                             min_weight_fraction_leaf=0.0,
                                             presort=False, random_state=None,
                                             splitter='best'),
             iid='warn', n_jobs=-1,
             param_grid={'criterion': ['mse', 'mae', 'friedman_mse'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=3)

In [10]:
# print best parameter after tuning 
#print(grid.best_params_) 
re=grid.cv_results_
#print(re)
grid_predictions = grid.predict(X_test) 
   
# print classification report 
from sklearn.metrics import r2_score
r_score=r2_score(y_test,grid_predictions)

print("The R_score value for best parameter {}:".format(grid.best_params_),r_score)

The R_score value for best parameter {'criterion': 'mse', 'max_features': 'auto', 'splitter': 'best'}: 0.8017566184604376

In [11]:
table=pd.DataFrame.from_dict(re)

In [12]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,mean_test_score,std_test_score,rank_test_score
0,0.008329,9.425725e-04,0.002665,4.708088e-04,mse,auto,best,"{'criterion': 'mse', 'max_features': 'auto', '...",0.828487,0.788829,0.803872,0.807067,0.016358,1
1,0.004665,4.721577e-04,0.001999,1.512074e-06,mse,auto,random,"{'criterion': 'mse', 'max_features': 'auto', '...",0.740124,0.681598,0.692184,0.704653,0.025478,6
2,0.004331,4.709211e-04,0.001999,5.619580e-07,mse,sqrt,best,"{'criterion': 'mse', 'max_features': 'sqrt', '...",0.763881,0.701100,0.577665,0.681033,0.077311,8
3,0.004664,2.355840e-03,0.002000,1.168008e-06,mse,sqrt,random,"{'criterion': 'mse', 'max_features': 'sqrt', '...",0.580571,0.523838,0.531549,0.545340,0.025137,17
4,0.004665,4.718766e-04,0.002000,5.840039e-07,mse,log2,best,"{'criterion': 'mse', 'max_features': 'log2', '...",0.683589,0.733055,0.692846,0.703179,0.021484,7
5,0.003332,4.737869e-04,0.002331,4.732277e-04,mse,log2,random,"{'criterion': 'mse', 'max_features': 'log2', '...",0.733966,0.646232,0.621105,0.667168,0.048384,10
6,0.045971,2.158398e-03,0.002000,8.174107e-04,mae,auto,best,"{'criterion': 'mae', 'max_features': 'auto', '...",0.793735,0.756149,0.765332,0.771748,0.016009,3
7,0.025985,2.447366e-03,0.001999,3.371748e-07,mae,auto,random,"{'criterion': 'mae', 'max_features': 'auto', '...",0.724909,0.802352,0.632816,0.720153,0.069270,5
8,0.021987,5.712197e-03,0.005331,4.709995e-03,mae,sqrt,best,"{'criterion': 'mae', 'max_features': 'sqrt', '...",0.632377,0.690072,0.708017,0.676776,0.032272,9
9,0.013658,1.245430e-03,0.001666,4.713147e-04,mae,sqrt,random,"{'criterion': 'mae', 'max_features': 'sqrt', '...",0.571505,0.559625,0.558598,0.563249,0.005859,16
10,0.023652,2.355503e-03,0.005331,4.711512e-03,mae,log2,best,"{'criterion': 'mae', 'max_features': 'log2', '...",0.589000,0.592247,0.666700,0.615909,0.035861,12
11,0.015990,8.166327e-04,0.002666,4.715406e-04,mae,log2,random,"{'criterion': 'mae', 'max_features': 'log2', '...",0.592319,0.567175,0.614672,0.591354,0.019396,14
12,0.006329,4.712018e-04,0.003332,1.247171e-03,friedman_mse,auto,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.839138,0.786812,0.779310,0.801786,0.026617,2
13,0.003664,4.708646e-04,0.001666,4.704714e-04,friedman_mse,auto,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.759828,0.752539,0.789186,0.767153,0.015829,4
14,0.003665,4.709772e-04,0.001999,4.495664e-07,friedman_mse,sqrt,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.629918,0.562187,0.599613,0.597236,0.027722,13
15,0.003664,9.429094e-04,0.001333,4.706960e-04,friedman_mse,sqrt,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.587038,0.524836,0.428467,0.513571,0.065202,18
16,0.003998,8.485379e-07,0.002666,9.418421e-04,friedman_mse,log2,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.712690,0.684535,0.550967,0.649541,0.070494,11
17,0.003000,8.158534e-04,0.001666,9.415044e-04,friedman_mse,log2,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.459764,0.547173,0.735380,0.580547,0.114933,15

In [13]:
cement_input=float(input("Cement:"))
slag_input=float(input("Slag:"))
flyash_input=float(input("Flyash:"))
water_input=float(input("Water:"))
superplasticizer_input=float(input("Superplasticizer:"))
coarseaggregate_input=float(input("Coarseaggregate:"))
fineaggregate_input=float(input("Fineaggregate:"))
age_input=int(input("Age:"))

Cement:546.2
Slag:96.4
Flyash:0.0
Water:122.9
Superplasticizer:35.9
Coarseaggregate:1015.2
Fineaggregate:999.6
Age:365

In [14]:
Future_Prediction=grid.predict([[cement_input,slag_input,flyash_input,water_input,superplasticizer_input,coarseaggregate_input,fineaggregate_input,age_input]])# change the paramter,play with it.
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[80.2]